### PR TITLE
Logs

### LINKED ISSUE #358: general logging and monitoring
* [ ] informative process logging
* [ ] exception handling unification
* [ ] (optional) performance monitoring

### PR DESCRIPTION
**Pull request by jaakkonarhi**
# Description of the PR

+ Closes #358 

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>e2e</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [x] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [x] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>e2e</b> tests created</li>
        <li>- [ ] all <b>e2e</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/master/TESTING.md) or other relevant documentation on _your_ branch?

- [ ] Yes.
- [ ] Not yet. I will do it next.
- [x] Not relevant.

### CODE REVIEW

**Review by stellatsv — APPROVED** [review]

File: src/main/java/fi/aalto/cs/apluscourses/intellij/activities/InitializationActivity.java [hunk 1]
```diff
@@ -59,18 +60,25 @@ public InitializationActivity(@NotNull Notifier notifier) {
 
   @Override
   public void runActivity(@NotNull Project project) {
+    final var stopwatch = new Stopwatch();
+    logger.info("Starting initialization");
+    logger.info("A+ Courses v{}", BuildInfo.INSTANCE.pluginVersion);
+    var courseVersion = BuildInfo.INSTANCE.courseVersion;
+    logger.info("Course v{}", courseVersion);
+    logger.info("Logs made by Jaakko <3");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/activities/InitializationActivity.java:68]: There's no point writing four log entries for what's essentially one event. I suggest "Starting initialization, course version {courseVersion}".

1. "Starting initialization" - can be merged with 3.
2. The "A+ Courses {version}" entry is redundant, since the plugin version is already included in the logger's name.
3. Good, but replace the "v" with "version"
4. umm

File: src/main/java/fi/aalto/cs/apluscourses/intellij/activities/InitializationActivity.java [hunk 2]
```diff
@@ -59,18 +60,25 @@ public InitializationActivity(@NotNull Notifier notifier) {
...
 
     var progressViewModel
-            = PluginSettings.getInstance().getMainViewModel(project).progressViewModel;
+        = PluginSettings.getInstance().getMainViewModel(project).progressViewModel;
 
     URL courseConfigurationFileUrl = getCourseUrlFromProject(project);
     if (courseConfigurationFileUrl == null) {
       isInitialized(project).set(true);
       progressViewModel.stopAll();
+      logger.info("No course configuration found");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/activities/InitializationActivity.java:81]: info -> warn/error (exercise judgment in determining how serious this is)

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/SubmitExerciseAction.java [hunk 3]
```diff
@@ -282,9 +300,11 @@ private void trySubmit(@NotNull Project project)
         submission.getPresentableExerciseName(),
         submission.getCurrentSubmissionNumber());
     addLocalHistoryTag(project, tag);
+    logger.info("Finished submitting exercise (took {}ms)", stopwatch.getTimeMs());
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/SubmitExerciseAction.java:303]: The time measurement is pointless here as it also includes time spent in the dialog window (but again, you shouldn't measure time, see other comments)

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/InstallModuleAction.java [hunk 4]
```diff
@@ -60,16 +65,24 @@ public void update(@NotNull AnActionEvent e) {
 
   @Override
   public void actionPerformed(@NotNull AnActionEvent e) {
+    var stopwatch = new Stopwatch();
+    logger.info("Starting InstallModuleAction");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/InstallModuleAction.java:69]: info -> debug

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/SubmitExerciseAction.java [hunk 5]
```diff
@@ -163,6 +168,7 @@ public void update(@NotNull AnActionEvent e) {
 
   @Override
   public void actionPerformed(@NotNull AnActionEvent e) {
+    logger.info("Starting SubmitExerciseAction");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/SubmitExerciseAction.java:171]: info -> debug

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/SubmitExerciseAction.java [hunk 6]
```diff
@@ -198,10 +208,13 @@ private void trySubmit(@NotNull Project project)
     }
 
     Exercise exercise = selectedExercise.getModel();
+    logger.info("Submitting {}", exercise);
     var submissionInfo = exercise.getSubmissionInfo();
     String language = languageSource.getLanguage(project);
+    logger.info("Language: {}", language);
 
     if (!submissionInfo.isSubmittable(language)) {
+      logger.info("{} not submittable", exercise);
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/SubmitExerciseAction.java:217]: info -> warn

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/APlusAuthenticationAction.java [hunk 7]
```diff
@@ -64,9 +68,11 @@ public void update(@NotNull AnActionEvent e) {
 
   @Override
   public void actionPerformed(@NotNull AnActionEvent e) {
+    logger.info("Starting APlusAuthenticationAction");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/APlusAuthenticationAction.java:71]: info -> debug

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/APlusAuthenticationAction.java [hunk 8]
```diff
@@ -64,9 +68,11 @@ public void update(@NotNull AnActionEvent e) {
...
     Project project = e.getProject();
     var courseProject = courseProjectProvider.getCourseProject(project);
     if (courseProject == null) {
+      logger.info("Course project was null");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/APlusAuthenticationAction.java:75]: info -> warn

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java [hunk 9]
```diff
@@ -147,6 +147,7 @@ public CourseProjectAction() {
 
   @Override
   public void actionPerformed(@NotNull AnActionEvent e) {
+    logger.info("Starting CourseProjectAction");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java:150]: info -> debug

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java [hunk 10]
```diff
@@ -163,11 +164,16 @@ public void actionPerformed(@NotNull AnActionEvent e) {
...
+    var version = BuildInfo.INSTANCE.courseVersion;
+    var versionComparison = version.compareTo(course.getVersion());
 
     if (versionComparison == Version.ComparisonStatus.MAJOR_TOO_OLD
         || versionComparison == Version.ComparisonStatus.MAJOR_TOO_NEW) {
+      if (versionComparison == Version.ComparisonStatus.MAJOR_TOO_OLD) {
+        logger.error("A+ Courses version outdated: installed v{}, required v{}", version, course.getVersion());
+      } else {
+        logger.error("A+ Courses version too new: installed v{}, required v{}", version, course.getVersion());
+      }
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java:176]: Remove "v" from version specifications

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java [hunk 11]
```diff
@@ -176,16 +182,20 @@ public void actionPerformed(@NotNull AnActionEvent e) {
 
     CourseProjectViewModel courseProjectViewModel
         = new CourseProjectViewModel(course, settingsImporter.currentlyImportedIdeSettings());
+    logger.info("Showing main dialog");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java:185]: "Showing a dialog" isn't a log-worthy event

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java [hunk 12]
```diff
@@ -176,16 +182,20 @@ public void actionPerformed(@NotNull AnActionEvent e) {
...
     if (!dialogs.showMainDialog(project, courseProjectViewModel)) {
+      logger.info("Canceled");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java:187]: Canceling a dialog also isn't log-worthy

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java [hunk 13]
```diff
@@ -274,8 +293,10 @@ private URL tryGetCourseUrl(@NotNull Project project) {
   @Nullable
   private Course tryGetCourse(@NotNull Project project, @NotNull URL courseUrl) {
     try {
+      logger.info("Getting course");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java:296]: info -> debug

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java [hunk 14]
```diff
@@ -301,6 +322,7 @@ private boolean tryCreateCourseFile(@NotNull Project project,
                                       @NotNull URL courseUrl,
                                       @NotNull String language) {
     try {
+      logger.info("Creating course file");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/CourseProjectAction.java:325]: info -> debug

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/DownloadSubmissionAction.java [hunk 15]
```diff
@@ -123,6 +129,7 @@ public DownloadSubmissionAction(@NotNull MainViewModelProvider mainViewModelProv
 
   @Override
   public void actionPerformed(@NotNull AnActionEvent e) {
+    logger.info("Starting DownloadSubmissionAction");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/DownloadSubmissionAction.java:132]: info -> debug

File: src/main/java/fi/aalto/cs/apluscourses/intellij/actions/DownloadSubmissionAction.java [hunk 16]
```diff
@@ -204,25 +221,33 @@ private void downloadFiles(@Nullable Project project,
...
+    logger.info("Starting download");
+    var stopwatch = new Stopwatch();
     for (var info : submissionFilesInfo) {
       try {
         var file = fileFinder.findFile(module.getFullPath(), info.getFileName()).toFile();
+        logger.info("Found file: {}", file);
         CoursesClient.fetch(new URL(info.getUrl()), file, auth);
+        logger.info("Fetched file");
         fileBrowser.navigateTo(file, project);
+        logger.info("Opened file");
```
Comment (Taikelenn) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/actions/DownloadSubmissionAction.java:241]: Only the first log entry is useful. The remaining entries don't give any additional information, and if something goes wrong then an exception is thrown and the log entries in `catch` clauses take over.

**Review by Taikelenn — COMMENTED** [review]
My comments/complaints:
- Don't measure time yourself, the log file already does it for you by providing timestamps. The class `Stopwatch` should ideally be deleted.
- Use also other logging levels than `info` and `error`. In short: use `error` for exceptions and other unexpected errors. Use `warn` for cases where an action cannot proceed, but it's not due to an unexpected error (for example: the user is missing a module, the user hasn't authenticated). Use `debug` for "pointless" messages that don't bring any useful data to the log file (like "Starting ActionXYZ"). Use `info` otherwise.
- Actions such as "showing dialog", "dialog canceled" shouldn't be logged. Mere fact that a UI dialog has been shown doesn't provide any value.
- Versions should be logged as "1.4", not "v1.4". The latter is redundant, especially in log entries which have a strict format and it's obvious that a version string is expected.

**Review by Taikelenn — APPROVED** [review]
