### PR TITLE
Fixed file path bug

### LINKED ISSUE #360: Scala compiler issue with O1Lib
#### Describe the bug
In some cases, the following appears (see screenshot)

#### To Reproduce
1. Try to run GoodStuff for the first time
2. See error
photo_2020-08-31_09-02-51

#### Expected behavior
Shows the hotel reservation system GUI.

#### Environment (please complete the following information):
 - Operating System: **Windows 10** / **macOS**
 - IntelliJ IDEA version (found from **Help > About**): [e.g. IntelliJ IDEA 2020.2. (Community Edition)]
 - Version of A+ Courses plugin (found from **A+ > About**): appeared for both types of installations: with and without plugin

### PR DESCRIPTION
**Pull request by OlliKiljunen**
# Description of the PR

+ Fixes #360.

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [x] new <b>unit</b> tests created</li>
        <li>- [x] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [x] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [x] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](/TESTING.md) or other relevant documentation?

- [ ] Yes
- [ ] Not yet. I will do it next.
- [x] Not relevant

### CODE REVIEW

File: src/test/java/fi/aalto/cs/apluscourses/intellij/model/ScalaSdkTest.java [hunk 1]
```diff
@@ -97,4 +101,25 @@ public void testGetUrisWithInvalidArguments() {
...
+
+  @Test
+  public void testGetUrisWithWeirdCharacters() {
+    //  given
+    APlusProject aplusProject = new APlusProject(getProject());
+    ScalaSdk scalaSdk = new ScalaSdk("scala-sdk-2.12.10", aplusProject);
+    final String[] allClasses = {
+        "name with a space.jar",
+        "scändinåvian.jör",
+        "💩.emoji"
```
Comment (nikke234) [inline src/test/java/fi/aalto/cs/apluscourses/intellij/model/ScalaSdkTest.java:113]: :rofl:

**Review by superseacat — APPROVED** [review]
works, looks good, has tests, quick :+1:

**Review by nikke234 — APPROVED** [review]
works and tested, awesome!
