### PR TITLE
Fixed compiler classpath issue in 2020.3

### LINKED ISSUE #416: In IDEA 2020.3, Scala SDK compiler classpath is not written causing e.g. REPL to fail
See note about 6.1 in https://github.com/Aalto-LeTech/intellij-plugin/pull/414#issuecomment-707684068

### PR DESCRIPTION
**Pull request by OlliKiljunen**
# Description of the PR

+ This is for IJ 2020.3 !

+ Fixes #416

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [ ] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [ ] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](/TESTING.md) or other relevant documentation?

- [ ] Yes
- [x] Not yet. I will do it next.
- [x] Not relevant

### CODE REVIEW

File: src/main/java/fi/aalto/cs/apluscourses/intellij/model/IntelliJLibrary.java [hunk 1]
```diff
@@ -42,8 +42,13 @@ protected void loadInternal() {
     for (String uri : getUris()) {
       library.addRoot(uri, OrderRootType.CLASSES);
     }
+
     //HACK: this is the only way to access properties that I am aware of
-    initializeLibraryProperties(((LibraryEx) library).getProperties());
+    LibraryEx.ModifiableModelEx libraryEx = (LibraryEx.ModifiableModelEx) library;
+    LibraryProperties<S> properties = libraryEx.getProperties();
+    initializeLibraryProperties(properties);
+    libraryEx.setProperties(properties);
```
Comment (nikke234) [inline src/main/java/fi/aalto/cs/apluscourses/intellij/model/IntelliJLibrary.java:50]: Just to make sure, does this still keep working for 2020.2?

File: src/test/scala/fi/aalto/cs/apluscourses/intellij/actions/ReplActionTest.scala [hunk 2]
```diff
@@ -6,9 +6,10 @@ import fi.aalto.cs.apluscourses.intellij.TestHelperScala
 import fi.aalto.cs.apluscourses.intellij.services.PluginSettings
 import fi.aalto.cs.apluscourses.intellij.utils.ModuleUtils
 import org.junit.Assert._
-import org.junit.Test
+import org.junit.{Ignore, Test}
 import org.mockito.Mockito.{mock, when}
 
+@Ignore
```
Comment (nikke234) [inline src/test/scala/fi/aalto/cs/apluscourses/intellij/actions/ReplActionTest.scala:12]: Needs a `// temporary fix` comment that can be laughed at after a few years :smile:

**Review by nikke234 — APPROVED** [review]
Great! :+1: Left one question about whether this still works with 2020.2, but assuming that it does, I approve! :heavy_check_mark:

File: build.gradle [hunk 3]
```diff
@@ -21,23 +21,23 @@ repositories {
...
         exclude group:'org.codehaus.groovy', module: 'groovy-xml'
     }
 }
 
 intellij {
     //  this is the version of the IntelliJ IDEA API (SDK) used to build the plugin
-    version '2020.2'
-    plugins = ['java', 'org.intellij.scala:2020.2.23']
+    version '2020.3'
+    plugins = ['java', 'org.intellij.scala:2020.3.15']
```
Comment (nikke234) [inline build.gradle:40]: Nikolai pointed out that 3.16 is out, so we could update to that

File: src/test/scala/fi/aalto/cs/apluscourses/intellij/actions/ReplActionTest.scala (hunk 2 above)
Comment (superseacat) [reply src/test/scala/fi/aalto/cs/apluscourses/intellij/actions/ReplActionTest.scala:12]: yepp, temporary)

**Review by superseacat — APPROVED** [review]
looks good!

File: src/main/java/fi/aalto/cs/apluscourses/intellij/model/IntelliJLibrary.java (hunk 1 above)
Comment (OlliKiljunen) [reply src/main/java/fi/aalto/cs/apluscourses/intellij/model/IntelliJLibrary.java:50]: Apparently, this code works also in 2020.2.

But because of the changes in **build.gradle**, the plug-in, as such, is not compatible with IDEA 2020.2, and cannot be installed to it. So once we release this, users must update their IntelliJ to 2020.3 to get this update.

But as I said, it seems that this piece of code works also in the older version of IntelliJ. Recap of what this change is about: Basically, what was changed here, is the addition of line 50; previously properties were got with `getProperties()` and modified inside `initializeLibraryProperties()` (just like in the new code), but they were never set back with `setProperties()`. In the old version, it however worked because `getProperties()` returned the reference to the same `LibraryProperties` object that the object itself use (so, calling `setProperties()` changed nothing). In the new version, `getProperties()` returns a copy of the properties object, so the modifications have no effect unless `setProperties()` is called.

File: src/test/scala/fi/aalto/cs/apluscourses/intellij/actions/ReplActionTest.scala (hunk 2 above)
Comment (OlliKiljunen) [reply src/test/scala/fi/aalto/cs/apluscourses/intellij/actions/ReplActionTest.scala:12]: I'm sure that the remark of passed tests in each run of tests is enough to keep this issue in mind.

**Comment by OlliKiljunen** [comment]
@nikke234:
> Left one question about whether this still works with 2020.2, but assuming that it does, I approve!

See [this comment](https://github.com/Aalto-LeTech/intellij-plugin/pull/428#discussion_r537544061). Anyway, I merge.
